#!/usr/bin/env bash
# Interactively create ~/.config/requests-unifi-auth/e2e.env (outside the git tree).
set -euo pipefail

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/requests-unifi-auth"
CONFIG_FILE="${UNIFI_E2E_CONFIG:-$CONFIG_DIR/e2e.env}"
CONFIG_PARENT="$(dirname -- "$CONFIG_FILE")"

umask 077

if [[ -t 0 ]]; then
  :
else
  echo "This script needs an interactive terminal (stdin is not a TTY)." >&2
  exit 1
fi

if [[ -e "$CONFIG_FILE" ]]; then
  read -r -p "File already exists at $CONFIG_FILE. Overwrite? [y/N] " overwrite
  case "$overwrite" in
    y|Y|yes|YES) ;;
    *)
      echo "Aborted."
      exit 0
      ;;
  esac
fi

if [[ ! -d "$CONFIG_PARENT" ]]; then
  mkdir -p -- "$CONFIG_PARENT"
  chmod 700 -- "$CONFIG_PARENT"
fi

if [[ -L "$CONFIG_FILE" ]]; then
  echo "Refusing to replace symlink at $CONFIG_FILE." >&2
  exit 1
fi

echo "Live e2e credentials (values are written only to $CONFIG_FILE)."
echo

read -r -p "Controller host (UNIFI_E2E_HOST) [192.168.1.1]: " host
host="${host:-192.168.1.1}"

read -r -p "Username (UNIFI_E2E_USERNAME) [e2e-requests-unifi-auth]: " username
username="${username:-e2e-requests-unifi-auth}"

while true; do
  IFS= read -r -s -p "Password (UNIFI_E2E_PASSWORD): " password
  echo
  if [[ -z "$password" ]]; then
    echo "Password must not be empty." >&2
    continue
  fi
  IFS= read -r -s -p "Confirm password: " password_confirm
  echo
  if [[ "$password" == "$password_confirm" ]]; then
    break
  fi
  echo "Passwords do not match; try again." >&2
done

read -r -p "Verify TLS certificates? (UNIFI_E2E_VERIFY_SSL) [false]: " verify_ssl
verify_ssl="${verify_ssl:-false}"

read -r -p "Enable disposable write test? (UNIFI_E2E_ENABLE_WRITE) [false]: " enable_write
enable_write="${enable_write:-false}"

dotenv_quote() {
  local value="$1"
  value=${value//\'/\'\\\'\'}
  printf "'%s'" "$value"
}

config_tmp="$(mktemp "${CONFIG_FILE}.tmp.XXXXXX")"
trap 'rm -f -- "$config_tmp"' EXIT

{
  printf '%s\n' '# Generated by scripts/init_e2e_config.sh — do not commit.'
  printf 'UNIFI_E2E_HOST='; dotenv_quote "$host"; printf '\n'
  printf 'UNIFI_E2E_USERNAME='; dotenv_quote "$username"; printf '\n'
  printf 'UNIFI_E2E_PASSWORD='; dotenv_quote "$password"; printf '\n'
  printf 'UNIFI_E2E_VERIFY_SSL='; dotenv_quote "$verify_ssl"; printf '\n'
  printf 'UNIFI_E2E_ENABLE_WRITE='; dotenv_quote "$enable_write"; printf '\n'
} >"$config_tmp"
chmod 600 "$config_tmp"
mv -f -- "$config_tmp" "$CONFIG_FILE"
trap - EXIT

echo
echo "Wrote $CONFIG_FILE (mode 600)."
echo "Run: pytest -m e2e"
