#!/usr/bin/env bash
# Interactively create ~/.config/requests-unifi-auth/e2e.env (outside the git tree).
set -euo pipefail

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/requests-unifi-auth"
CONFIG_FILE="${UNIFI_E2E_CONFIG:-$CONFIG_DIR/e2e.env}"

if [[ -t 0 ]]; then
  :
else
  echo "This script needs an interactive terminal (stdin is not a TTY)." >&2
  exit 1
fi

mkdir -p "$CONFIG_DIR"
chmod 700 "$CONFIG_DIR"

if [[ -e "$CONFIG_FILE" ]]; then
  read -r -p "File already exists at $CONFIG_FILE. Overwrite? [y/N] " overwrite
  case "$overwrite" in
    y|Y|yes|YES) ;;
    *)
      echo "Aborted."
      exit 0
      ;;
  esac
fi

echo "Live e2e credentials (values are written only to $CONFIG_FILE)."
echo

read -r -p "Controller host (UNIFI_E2E_HOST) [192.168.1.1]: " host
host="${host:-192.168.1.1}"

read -r -p "Username (UNIFI_E2E_USERNAME) [e2e-requests-unifi-auth]: " username
username="${username:-e2e-requests-unifi-auth}"

while true; do
  read -r -s -p "Password (UNIFI_E2E_PASSWORD): " password
  echo
  if [[ -z "$password" ]]; then
    echo "Password must not be empty." >&2
    continue
  fi
  read -r -s -p "Confirm password: " password_confirm
  echo
  if [[ "$password" == "$password_confirm" ]]; then
    break
  fi
  echo "Passwords do not match; try again." >&2
done

read -r -p "Verify TLS certificates? (UNIFI_E2E_VERIFY_SSL) [false]: " verify_ssl
verify_ssl="${verify_ssl:-false}"

read -r -p "Skip disposable write test? (UNIFI_E2E_SKIP_WRITE) [false]: " skip_write
skip_write="${skip_write:-false}"

umask 077
cat >"$CONFIG_FILE" <<EOF
# Generated by scripts/init_e2e_config.sh — do not commit.
UNIFI_E2E_HOST=$host
UNIFI_E2E_USERNAME=$username
UNIFI_E2E_PASSWORD=$password
UNIFI_E2E_VERIFY_SSL=$verify_ssl
UNIFI_E2E_SKIP_WRITE=$skip_write
EOF
chmod 600 "$CONFIG_FILE"

echo
echo "Wrote $CONFIG_FILE (mode 600)."
echo "Run: pytest -m e2e"
